{ GENERATED by scripts/sync-register-hash.ps1 ? do NOT edit by hand.
  SHA-256 of installer/_shared/register-plugin.ps1, pinned into each uninstaller for the pre-exec tamper
  check (LPE mitigation, owner decision 2026-07-19 ? cert-free, no Authenticode). Regenerate whenever the
  .ps1 changes: just sync-register-hash (checked by just check-register-hash / pre-push). }
#define ExpectedRegisterPs1Sha256 "325F8F60A617394FF2C242ACA73AFF09B7A918780A53A595C9C70050A41CC193"
