Describe 'docs-audit-reminder.sh' {
    BeforeAll {
        . (Join-Path $PSScriptRoot 'BashHookHelpers.ps1')
        $repoRoot = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
        $script:Hook = Join-Path $repoRoot '.claude/hooks/docs-audit-reminder.sh'
        $script:Dash = [string][char]0x2014
        $script:Header = '# docs audit findings (GENERATED by scripts/docs-audit.ps1 - do not edit)'

        # A workspace whose docs/docs-audit-findings.md carries $Lines (null = no view at all).
        function New-Workspace { param([string[]]$Lines)
            $d = Join-Path ([IO.Path]::GetTempPath()) ("dar-" + [Guid]::NewGuid().ToString('N'))
            New-Item -ItemType Directory -Path (Join-Path $d 'docs') -Force | Out-Null
            if ($null -ne $Lines) {
                Set-Content -LiteralPath (Join-Path $d 'docs/docs-audit-findings.md') -Value ($Lines -join "`n") -Encoding utf8NoBOM
            }
            return $d
        }

        # Every path of this hook must be stderr-silent; the invariant lives in the WRAPPER so no row can forget it.
        function Invoke-Hook { param([string]$Dir)
            $r = Invoke-BashHook -HookPath $script:Hook -Env @{ CLAUDE_PROJECT_DIR = $Dir }
            $r.StdErr | Should -BeNullOrEmpty -Because 'a SessionStart hook that writes stderr is rendered as a failing hook'
            return $r
        }

        # Writes the view byte-exact: Set-Content appends its own newline, which would hide a missing-final-newline case.
        function Write-View { param([string]$Dir, [string]$Text) [IO.File]::WriteAllText((Join-Path $Dir 'docs/docs-audit-findings.md'), $Text, [Text.UTF8Encoding]::new($false)) }
    }

    It 'is silent when the view does not exist' {
        $d = New-Workspace -Lines $null
        $r = Invoke-Hook $d
        $r.StdOut | Should -BeNullOrEmpty
        $r.ExitCode | Should -Be 0
    }

    It 'is silent when every doc is CLEAN' {
        $d = New-Workspace -Lines @($script:Header, '', "## A.md $($script:Dash) CLEAN", '', '- (no findings)')
        $r = Invoke-Hook $d
        $r.StdOut | Should -BeNullOrEmpty
        $r.ExitCode | Should -Be 0
    }

    It 'names the open-finding count' {
        $d = New-Workspace -Lines @(
            $script:Header, '',
            "## A.md $($script:Dash) FINDINGS", '', '- one', '- two', '- three', '',
            "## B.md $($script:Dash) CLEAN", '', '- (no findings)')
        $r = Invoke-Hook $d
        $r.ExitCode | Should -Be 0
        $j = $r.StdOut | ConvertFrom-Json
        $j.systemMessage | Should -Match ([regex]::Escape('3 open finding(s)'))
        $j.systemMessage | Should -Match ([regex]::Escape('docs/docs-audit-findings.md'))
    }

    It 'counts a doc whose audit did not confirm' {
        $d = New-Workspace -Lines @($script:Header, '', "## X.md $($script:Dash) AUDIT-TIMEOUT (claims inspected: 0)", '', '- (no findings)')
        $r = Invoke-Hook $d
        $r.ExitCode | Should -Be 0
        $j = $r.StdOut | ConvertFrom-Json
        $j.systemMessage | Should -Match ([regex]::Escape('1 unconfirmed doc(s)'))
    }

    It 'counts every AUDIT-* outcome, and only in a section header' {
        # Three non-confirming outcomes, plus a finding whose TEXT mentions AUDIT-SUSPECT: the header anchor must
        # keep that bullet out of the unconfirmed count (it is one open finding, not a fourth unconfirmed doc).
        $d = New-Workspace -Lines @(
            $script:Header, '',
            "## X.md $($script:Dash) AUDIT-TIMEOUT (claims inspected: 0)", '', '- (no findings)', '',
            "## Y.md $($script:Dash) AUDIT-INCONCLUSIVE (claims inspected: 0)", '', '- (no findings)', '',
            "## Z.md $($script:Dash) AUDIT-SUSPECT (claims inspected: 1)", '', '- (no findings)', '',
            "## W.md $($script:Dash) FINDINGS", '', '- the doc says AUDIT-SUSPECT is terminal; it is not')
        $r = Invoke-Hook $d
        $r.ExitCode | Should -Be 0
        $j = $r.StdOut | ConvertFrom-Json
        $j.systemMessage | Should -Match ([regex]::Escape('1 open finding(s) and 3 unconfirmed doc(s)'))
    }

    # Capstone R3 (mutant: relax the section-header regex to drop the em-dash - the suite stayed green because every fixture used the
    # em-dash). The distractor is a near-miss header, a plain hyphen where the generated report writes U+2014.
    It 'does NOT count a near-miss header (hyphen, not the em-dash) as an unconfirmed doc' {
        $d = New-Workspace -Lines @($script:Header, '', "## A.md $($script:Dash) FINDINGS", '', '- one', '', '## X.md - AUDIT-TIMEOUT (claims inspected: 0)')
        $r = Invoke-Hook $d
        $r.ExitCode | Should -Be 0
        $j = $r.StdOut | ConvertFrom-Json
        $j.systemMessage | Should -Match ([regex]::Escape('1 open finding(s) and 0 unconfirmed doc(s)')) -Because 'only the em-dash header the generator writes is an audit outcome'
    }

    It 'emits the SessionStart envelope, with the nudge in additionalContext for the model' {
        $d = New-Workspace -Lines @($script:Header, '', "## A.md $($script:Dash) FINDINGS", '', '- one')
        $r = Invoke-Hook $d
        $j = $r.StdOut | ConvertFrom-Json
        $j.hookSpecificOutput.hookEventName | Should -BeExactly 'SessionStart'
        $j.hookSpecificOutput.additionalContext | Should -BeExactly $j.systemMessage
        $j.systemMessage | Should -Match ([regex]::Escape('1 open finding(s)'))
    }

    It 'warns on a view it does not recognise' {
        $d = New-Workspace -Lines @('hello', '', "## A.md $($script:Dash) FINDINGS", '', '- one')
        $r = Invoke-Hook $d
        $r.ExitCode | Should -Be 0
        $j = $r.StdOut | ConvertFrom-Json
        $j.systemMessage | Should -Match ([regex]::Escape('not a recognisable generated view'))
    }

    # --- BRANCH 21 (Task 7): the counting moved from tr + three greps to ONE builtin pass. The plan said the suite already
    # covered CRLF; it did not (no row wrote a CR). These rows are the preservation proof for the mechanism that changed. ---

    It 'counts a CRLF view exactly as it counts an LF one (the header and every "(no findings)" line end in CR)' {
        $dash = $script:Dash
        $lines = @($script:Header, '', "## A.md $dash FINDINGS", '', '- one', '- two', '', "## B.md $dash CLEAN", '', '- (no findings)')
        $d = New-Workspace -Lines $null
        Write-View $d (($lines -join "`r`n") + "`r`n")
        $j = (Invoke-Hook $d).StdOut | ConvertFrom-Json
        $j.systemMessage | Should -Match ([regex]::Escape('2 open finding(s)')) -Because 'a CR on "- (no findings)" must not stop it being recognised as the empty marker'
        # The all-clean CRLF view is the sharper half: if the CR defeated the empty marker, this would NAG with 1 open finding.
        $e = New-Workspace -Lines $null
        Write-View $e ((@($script:Header, '', "## A.md $dash CLEAN", '', '- (no findings)') -join "`r`n") + "`r`n")
        (Invoke-Hook $e).StdOut | Should -BeNullOrEmpty -Because 'a CRLF save of a clean view must stay silent'
    }

    It 'counts the LAST line when the file has no trailing newline' {
        $d = New-Workspace -Lines $null
        Write-View $d ($script:Header + "`n`n## A.md $($script:Dash) FINDINGS`n`n- one`n- the last, unterminated")
        ((Invoke-Hook $d).StdOut | ConvertFrom-Json).systemMessage | Should -Match ([regex]::Escape('2 open finding(s)'))
    }

    It 'counts only "- " bullets: near-misses (a dash with no space, a rule, an indented dash) are not findings' {
        $d = New-Workspace -Lines @($script:Header, '', "## A.md $($script:Dash) FINDINGS", '', '- real', '-no-space', '--- a rule', '  - indented', '* star', '(no findings)')
        ((Invoke-Hook $d).StdOut | ConvertFrom-Json).systemMessage | Should -Match ([regex]::Escape('1 open finding(s)'))
    }

    It 'reports an UNREADABLE view as unrecognisable rather than passing it silently' {
        # The failed-open case: an ACL-denied view must NOT read as "no findings". Probed from the bash process the hook
        # runs in (see agy-anomaly-reminder.Tests.ps1), and skipped on a host that does not enforce the deny.
        $d = New-Workspace -Lines @($script:Header, '', "## A.md $($script:Dash) FINDINGS", '', '- one')
        $f = Join-Path $d 'docs/docs-audit-findings.md'
        try {
            & icacls $f /deny "$($env:USERNAME):(R)" 2>&1 | Out-Null
            & (Get-GitBashOrThrow) -lc "cat '$($f -replace '\\','/')' > /dev/null 2>&1"
            if ($LASTEXITCODE -eq 0) { Set-ItResult -Skipped -Because 'this host does not enforce the read deny against the hook process'; return }
            $r = Invoke-Hook $d
            $r.ExitCode | Should -Be 0
            (($r.StdOut | ConvertFrom-Json).systemMessage) | Should -Match ([regex]::Escape('not a recognisable generated view'))
        } finally { & icacls $f /remove:d "$($env:USERNAME)" 2>&1 | Out-Null }
    }
}
