Describe 'docs-audit-reminder.sh' {
    BeforeAll {
        . (Join-Path $PSScriptRoot 'BashHookHelpers.ps1')
        $repoRoot = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
        $script:Hook = Join-Path $repoRoot '.claude/hooks/docs-audit-reminder.sh'
        $script:Dash = [string][char]0x2014
        $script:Header = '# docs audit findings (GENERATED by scripts/docs-audit.ps1 - do not edit)'

        # A workspace whose docs/docs-audit-findings.md carries $Lines (null = no view at all).
        function New-Workspace { param([string[]]$Lines)
            $d = Join-Path ([IO.Path]::GetTempPath()) ("dar-" + [Guid]::NewGuid().ToString('N'))
            New-Item -ItemType Directory -Path (Join-Path $d 'docs') -Force | Out-Null
            if ($null -ne $Lines) {
                Set-Content -LiteralPath (Join-Path $d 'docs/docs-audit-findings.md') -Value ($Lines -join "`n") -Encoding utf8NoBOM
            }
            return $d
        }

        # Every path of this hook must be stderr-silent; the invariant lives in the WRAPPER so no row can forget it.
        function Invoke-Hook { param([string]$Dir)
            $r = Invoke-BashHook -HookPath $script:Hook -Env @{ CLAUDE_PROJECT_DIR = $Dir }
            $r.StdErr | Should -BeNullOrEmpty -Because 'a SessionStart hook that writes stderr is rendered as a failing hook'
            return $r
        }
    }

    It 'is silent when the view does not exist' {
        $d = New-Workspace -Lines $null
        $r = Invoke-Hook $d
        $r.StdOut | Should -BeNullOrEmpty
        $r.ExitCode | Should -Be 0
    }

    It 'is silent when every doc is CLEAN' {
        $d = New-Workspace -Lines @($script:Header, '', "## A.md $($script:Dash) CLEAN", '', '- (no findings)')
        $r = Invoke-Hook $d
        $r.StdOut | Should -BeNullOrEmpty
        $r.ExitCode | Should -Be 0
    }

    It 'names the open-finding count' {
        $d = New-Workspace -Lines @(
            $script:Header, '',
            "## A.md $($script:Dash) FINDINGS", '', '- one', '- two', '- three', '',
            "## B.md $($script:Dash) CLEAN", '', '- (no findings)')
        $r = Invoke-Hook $d
        $r.ExitCode | Should -Be 0
        $j = $r.StdOut | ConvertFrom-Json
        $j.systemMessage | Should -Match ([regex]::Escape('3 open finding(s)'))
        $j.systemMessage | Should -Match ([regex]::Escape('docs/docs-audit-findings.md'))
    }

    It 'counts a doc whose audit did not confirm' {
        $d = New-Workspace -Lines @($script:Header, '', "## X.md $($script:Dash) AUDIT-TIMEOUT (claims inspected: 0)", '', '- (no findings)')
        $r = Invoke-Hook $d
        $r.ExitCode | Should -Be 0
        $j = $r.StdOut | ConvertFrom-Json
        $j.systemMessage | Should -Match ([regex]::Escape('1 unconfirmed doc(s)'))
    }

    It 'warns on a view it does not recognise' {
        $d = New-Workspace -Lines @('hello', '', "## A.md $($script:Dash) FINDINGS", '', '- one')
        $r = Invoke-Hook $d
        $r.ExitCode | Should -Be 0
        $j = $r.StdOut | ConvertFrom-Json
        $j.systemMessage | Should -Match ([regex]::Escape('not a recognisable generated view'))
    }
}
