#requires -Version 5.1
# Regenerate installer/_shared/register-plugin-hash.iss with the current SHA-256 of register-plugin.ps1.
# The hash is baked (as an ISPP #define) into every uninstaller that ships the loose script, which verifies
# it via Inno's native GetSHA256OfFile before exec — a cert-free tamper check (owner decision 2026-07-19).
$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$ps1  = Join-Path $root 'installer\_shared\register-plugin.ps1'
$out  = Join-Path $root 'installer\_shared\register-plugin-hash.iss'
$hash = (Get-FileHash -Algorithm SHA256 -Path $ps1).Hash.ToUpperInvariant()
$body = @"
{ GENERATED by scripts/sync-register-hash.ps1 — do NOT edit by hand.
  SHA-256 of installer/_shared/register-plugin.ps1, pinned into each uninstaller for the pre-exec tamper
  check (LPE mitigation, owner decision 2026-07-19 — cert-free, no Authenticode). Regenerate whenever the
  .ps1 changes: `just sync-register-hash` (checked by `just check-register-hash` / pre-push). }
#define ExpectedRegisterPs1Sha256 "$hash"
"@
Set-Content -Path $out -Value $body -Encoding ASCII -NoNewline:$false
Write-Host "register-plugin-hash.iss updated: $hash"
